# Generated by Django 4.0.1 on 2022-02-03 15:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0001_initial'),
        ('MoneyControlApp', '0002_alter_balchange_datetime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BalChange_EM',
            new_name='Operation_EM',
        ),
    ]
