# Generated by Django 4.0.1 on 2022-02-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyControlApp', '0002_alter_operation_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Operation_EM',
        ),
    ]
