# Generated by Django 4.0.2 on 2022-02-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyControlApp', '0003_delete_operation_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='name',
            field=models.CharField(default='Операция', max_length=50, verbose_name='Название'),
        ),
    ]
