# Generated by Django 4.0.1 on 2022-02-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='group',
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(default=2, max_length=30, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
